<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // CategoryID = 1: Mac (25 products)
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Pro 16" M2 Max 1TB',
                'Description' => 'Laptop cao cấp với chip M2 Max, dung lượng 1TB',
                'Price' => 3499.99,
                'Stock' => 20,
                'ImageURL' => 'macbookpro16_m2max_1tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Pro 16" M2 Pro 512GB',
                'Description' => 'Laptop chuyên nghiệp với chip M2 Pro, màn hình Retina',
                'Price' => 2499.99,
                'Stock' => 30,
                'ImageURL' => 'macbookpro16_m2pro_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Air 13" M2 256GB',
                'Description' => 'Laptop mỏng nhẹ với chip M2, pin 18 giờ',
                'Price' => 1199.99,
                'Stock' => 60,
                'ImageURL' => 'macbookair13_m2_256gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Air 15" M2 512GB',
                'Description' => 'Laptop mỏng nhẹ với màn hình lớn 15 inch',
                'Price' => 1499.99,
                'Stock' => 50,
                'ImageURL' => 'macbookair15_m2_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'iMac 24" M1 256GB Blue',
                'Description' => 'Máy tính all-in-one màu xanh, chip M1',
                'Price' => 1299.99,
                'Stock' => 35,
                'ImageURL' => 'imac24_m1_blue.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'iMac 24" M1 512GB Silver',
                'Description' => 'Máy tính all-in-one màu bạc, chip M1',
                'Price' => 1499.99,
                'Stock' => 30,
                'ImageURL' => 'imac24_m1_silver.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'Mac Mini M2 256GB',
                'Description' => 'Máy tính để bàn nhỏ gọn với chip M2',
                'Price' => 599.99,
                'Stock' => 70,
                'ImageURL' => 'macmini_m2_256gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'Mac Mini M2 Pro 512GB',
                'Description' => 'Máy tính để bàn hiệu năng cao với chip M2 Pro',
                'Price' => 1299.99,
                'Stock' => 40,
                'ImageURL' => 'macmini_m2pro_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'Mac Studio M1 Ultra 1TB',
                'Description' => 'Máy tính chuyên nghiệp cho công việc sáng tạo',
                'Price' => 3999.99,
                'Stock' => 15,
                'ImageURL' => 'macstudio_m1ultra_1tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Pro 14" M2 Max 1TB',
                'Description' => 'Laptop hiệu năng cao với chip M2 Max',
                'Price' => 3099.99,
                'Stock' => 25,
                'ImageURL' => 'macbookpro14_m2max_1tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Pro 13" M2 512GB',
                'Description' => 'Laptop với Touch Bar và chip M2',
                'Price' => 1499.99,
                'Stock' => 45,
                'ImageURL' => 'macbookpro13_m2_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'Mac Pro M2 Ultra 2TB',
                'Description' => 'Máy tính chuyên dụng cho công việc nặng',
                'Price' => 7999.99,
                'Stock' => 10,
                'ImageURL' => 'macpro_m2ultra_2tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Air 13" M3 512GB',
                'Description' => 'Laptop mỏng nhẹ với chip M3 mới nhất',
                'Price' => 1399.99,
                'Stock' => 55,
                'ImageURL' => 'macbookair13_m3_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'iMac 27" M1 Pro 1TB',
                'Description' => 'Máy tính all-in-one với chip M1 Pro',
                'Price' => 1999.99,
                'Stock' => 25,
                'ImageURL' => 'imac27_m1pro_1tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Pro 16" M3 Max 2TB',
                'Description' => 'Laptop cao cấp với chip M3 Max, dung lượng 2TB',
                'Price' => 3999.99,
                'Stock' => 15,
                'ImageURL' => 'macbookpro16_m3max_2tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Air 15" M3 1TB',
                'Description' => 'Laptop mỏng nhẹ với chip M3, màn hình 15 inch',
                'Price' => 1699.99,
                'Stock' => 40,
                'ImageURL' => 'macbookair15_m3_1tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'Mac Mini M3 512GB',
                'Description' => 'Máy tính để bàn nhỏ gọn với chip M3',
                'Price' => 799.99,
                'Stock' => 60,
                'ImageURL' => 'macmini_m3_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'iMac 24" M2 1TB Green',
                'Description' => 'Máy tính all-in-one màu xanh lá, chip M2',
                'Price' => 1599.99,
                'Stock' => 30,
                'ImageURL' => 'imac24_m2_green.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Pro 14" M3 Pro 512GB',
                'Description' => 'Laptop hiệu năng cao với chip M3 Pro',
                'Price' => 1999.99,
                'Stock' => 35,
                'ImageURL' => 'macbookpro14_m3pro_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'Mac Studio M2 Ultra 2TB',
                'Description' => 'Máy tính chuyên nghiệp với chip M2 Ultra',
                'Price' => 4999.99,
                'Stock' => 12,
                'ImageURL' => 'macstudio_m2ultra_2tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Air 13" M2 1TB Space Gray',
                'Description' => 'Laptop mỏng nhẹ màu xám không gian, chip M2',
                'Price' => 1599.99,
                'Stock' => 50,
                'ImageURL' => 'macbookair13_m2_spacegray.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'iMac 24" M2 512GB Pink',
                'Description' => 'Máy tính all-in-one màu hồng, chip M2',
                'Price' => 1499.99,
                'Stock' => 35,
                'ImageURL' => 'imac24_m2_pink.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Pro 16" M2 Max 512GB',
                'Description' => 'Laptop cao cấp với chip M2 Max, màn hình Liquid Retina',
                'Price' => 3299.99,
                'Stock' => 20,
                'ImageURL' => 'macbookpro16_m2max_512gb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'Mac Mini M2 1TB',
                'Description' => 'Máy tính để bàn nhỏ gọn với dung lượng 1TB',
                'Price' => 999.99,
                'Stock' => 50,
                'ImageURL' => 'macmini_m2_1tb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 1,
                'ProductName' => 'MacBook Air 13" M3 256GB Midnight',
                'Description' => 'Laptop mỏng nhẹ màu xanh đêm, chip M3',
                'Price' => 1299.99,
                'Stock' => 60,
                'ImageURL' => 'macbookair13_m3_midnight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // CategoryID = 2: iPhone (25 products)
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Pro Max 256GB Black',
                'Description' => 'Điện thoại cao cấp với camera 48MP, chip A17 Pro',
                'Price' => 1299.99,
                'Stock' => 80,
                'ImageURL' => 'iphone15promax_256gb_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Pro 512GB White',
                'Description' => 'Điện thoại cao cấp với chip A17 Pro, màu trắng',
                'Price' => 1399.99,
                'Stock' => 70,
                'ImageURL' => 'iphone15pro_512gb_white.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 128GB Blue',
                'Description' => 'Điện thoại tiêu chuẩn với chip A16 Bionic, màu xanh',
                'Price' => 899.99,
                'Stock' => 100,
                'ImageURL' => 'iphone15_128gb_blue.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Plus 256GB Pink',
                'Description' => 'Điện thoại màn hình lớn với chip A16 Bionic',
                'Price' => 999.99,
                'Stock' => 85,
                'ImageURL' => 'iphone15plus_256gb_pink.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 Pro 256GB Space Black',
                'Description' => 'Điện thoại cao cấp với Dynamic Island, camera 48MP',
                'Price' => 1099.99,
                'Stock' => 90,
                'ImageURL' => 'iphone14pro_256gb_spaceblack.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 128GB Midnight',
                'Description' => 'Điện thoại tiêu chuẩn với chip A15 Bionic',
                'Price' => 799.99,
                'Stock' => 120,
                'ImageURL' => 'iphone14_128gb_midnight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 13 Mini 128GB Starlight',
                'Description' => 'Điện thoại nhỏ gọn với chip A15 Bionic',
                'Price' => 699.99,
                'Stock' => 80,
                'ImageURL' => 'iphone13mini_128gb_starlight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone SE 2023 64GB Red',
                'Description' => 'Điện thoại giá rẻ với chip A15 Bionic, màu đỏ',
                'Price' => 429.99,
                'Stock' => 150,
                'ImageURL' => 'iphonese2023_64gb_red.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 Pro Max 512GB Gold',
                'Description' => 'Điện thoại cao cấp với màn hình lớn, camera 48MP',
                'Price' => 1399.99,
                'Stock' => 60,
                'ImageURL' => 'iphone14promax_512gb_gold.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Pro 1TB Blue Titanium',
                'Description' => 'Điện thoại cao cấp với dung lượng 1TB, chip A17 Pro',
                'Price' => 1599.99,
                'Stock' => 50,
                'ImageURL' => 'iphone15pro_1tb_bluetitanium.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 256GB Yellow',
                'Description' => 'Điện thoại tiêu chuẩn với chip A16 Bionic, màu vàng',
                'Price' => 999.99,
                'Stock' => 90,
                'ImageURL' => 'iphone15_256gb_yellow.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 Plus 128GB Purple',
                'Description' => 'Điện thoại màn hình lớn với chip A15 Bionic',
                'Price' => 899.99,
                'Stock' => 100,
                'ImageURL' => 'iphone14plus_128gb_purple.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 13 256GB Green',
                'Description' => 'Điện thoại với chip A15 Bionic, màu xanh lá',
                'Price' => 799.99,
                'Stock' => 85,
                'ImageURL' => 'iphone13_256gb_green.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Pro Max 512GB Natural Titanium',
                'Description' => 'Điện thoại cao cấp với camera 48MP, chip A17 Pro',
                'Price' => 1499.99,
                'Stock' => 65,
                'ImageURL' => 'iphone15promax_512gb_natural.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 256GB Blue',
                'Description' => 'Điện thoại tiêu chuẩn với chip A15 Bionic, màu xanh',
                'Price' => 899.99,
                'Stock' => 110,
                'ImageURL' => 'iphone14_256gb_blue.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone SE 2023 128GB Black',
                'Description' => 'Điện thoại giá rẻ với chip A15 Bionic, màu đen',
                'Price' => 479.99,
                'Stock' => 140,
                'ImageURL' => 'iphonese2023_128gb_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Plus 512GB Green',
                'Description' => 'Điện thoại màn hình lớn với chip A16 Bionic',
                'Price' => 1099.99,
                'Stock' => 75,
                'ImageURL' => 'iphone15plus_512gb_green.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 13 Pro 256GB Graphite',
                'Description' => 'Điện thoại cao cấp với camera ProMotion',
                'Price' => 999.99,
                'Stock' => 80,
                'ImageURL' => 'iphone13pro_256gb_graphite.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 Pro 128GB Silver',
                'Description' => 'Điện thoại cao cấp với Dynamic Island, màu bạc',
                'Price' => 999.99,
                'Stock' => 95,
                'ImageURL' => 'iphone14pro_128gb_silver.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 512GB Black',
                'Description' => 'Điện thoại tiêu chuẩn với chip A16 Bionic, màu đen',
                'Price' => 1099.99,
                'Stock' => 85,
                'ImageURL' => 'iphone15_512gb_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 Pro Max 1TB Purple',
                'Description' => 'Điện thoại cao cấp với dung lượng 1TB, màu tím',
                'Price' => 1599.99,
                'Stock' => 50,
                'ImageURL' => 'iphone14promax_1tb_purple.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 13 Mini 256GB Pink',
                'Description' => 'Điện thoại nhỏ gọn với chip A15 Bionic, màu hồng',
                'Price' => 799.99,
                'Stock' => 90,
                'ImageURL' => 'iphone13mini_256gb_pink.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Pro 256GB Gold',
                'Description' => 'Điện thoại cao cấp với chip A17 Pro, màu vàng',
                'Price' => 1299.99,
                'Stock' => 70,
                'ImageURL' => 'iphone15pro_256gb_gold.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 14 512GB Red',
                'Description' => 'Điện thoại tiêu chuẩn với chip A15 Bionic, màu đỏ',
                'Price' => 999.99,
                'Stock' => 100,
                'ImageURL' => 'iphone14_512gb_red.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 2,
                'ProductName' => 'iPhone 15 Pro Max 1TB White Titanium',
                'Description' => 'Điện thoại cao cấp với dung lượng 1TB, chip A17 Pro',
                'Price' => 1699.99,
                'Stock' => 45,
                'ImageURL' => 'iphone15promax_1tb_white.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // CategoryID = 3: AirPods (25 products)
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Pro 2',
                'Description' => 'Tai nghe không dây với chống ồn cải tiến',
                'Price' => 279.99,
                'Stock' => 180,
                'ImageURL' => 'airpodspro2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 3rd Gen',
                'Description' => 'Tai nghe không dây với âm thanh không gian',
                'Price' => 179.99,
                'Stock' => 200,
                'ImageURL' => 'airpods3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Max Silver',
                'Description' => 'Tai nghe over-ear cao cấp, màu bạc',
                'Price' => 549.99,
                'Stock' => 50,
                'ImageURL' => 'airpodsmax_silver.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 2nd Gen',
                'Description' => 'Tai nghe không dây giá rẻ, chất lượng tốt',
                'Price' => 129.99,
                'Stock' => 220,
                'ImageURL' => 'airpods2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Pro 1st Gen',
                'Description' => 'Tai nghe không dây với chống ồn chủ động',
                'Price' => 249.99,
                'Stock' => 150,
                'ImageURL' => 'airpodspro1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 4th Gen',
                'Description' => 'Tai nghe không dây với thiết kế mới',
                'Price' => 199.99,
                'Stock' => 170,
                'ImageURL' => 'airpods4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Max Space Gray',
                'Description' => 'Tai nghe over-ear cao cấp, màu xám không gian',
                'Price' => 549.99,
                'Stock' => 45,
                'ImageURL' => 'airpodsmax_spacegray.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Pro 2 USB-C',
                'Description' => 'Tai nghe không dây với cổng USB-C, chống ồn cải tiến',
                'Price' => 299.99,
                'Stock' => 160,
                'ImageURL' => 'airpodspro2_usbc.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 3rd Gen MagSafe',
                'Description' => 'Tai nghe không dây với hộp sạc MagSafe',
                'Price' => 189.99,
                'Stock' => 190,
                'ImageURL' => 'airpods3_magsafe.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Max Green',
                'Description' => 'Tai nghe over-ear cao cấp, màu xanh lá',
                'Price' => 549.99,
                'Stock' => 40,
                'ImageURL' => 'airpodsmax_green.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 2nd Gen Wireless',
                'Description' => 'Tai nghe không dây với hộp sạc không dây',
                'Price' => 159.99,
                'Stock' => 200,
                'ImageURL' => 'airpods2_wireless.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Pro 2 Black',
                'Description' => 'Tai nghe không dây màu đen, chống ồn cải tiến',
                'Price' => 289.99,
                'Stock' => 170,
                'ImageURL' => 'airpodspro2_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 4th Gen ANC',
                'Description' => 'Tai nghe không dây với chống ồn chủ động',
                'Price' => 229.99,
                'Stock' => 160,
                'ImageURL' => 'airpods4_anc.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Max Pink',
                'Description' => 'Tai nghe over-ear cao cấp, màu hồng',
                'Price' => 549.99,
                'Stock' => 40,
                'ImageURL' => 'airpodsmax_pink.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 3rd Gen Limited Edition',
                'Description' => 'Tai nghe không dây phiên bản giới hạn',
                'Price' => 199.99,
                'Stock' => 100,
                'ImageURL' => 'airpods3_limited.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Pro 1st Gen Refurbished',
                'Description' => 'Tai nghe không dây tân trang, chống ồn chủ động',
                'Price' => 199.99,
                'Stock' => 120,
                'ImageURL' => 'airpodspro1_refurbished.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Max Blue',
                'Description' => 'Tai nghe over-ear cao cấp, màu xanh dương',
                'Price' => 549.99,
                'Stock' => 45,
                'ImageURL' => 'airpodsmax_blue.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 4th Gen Wireless',
                'Description' => 'Tai nghe không dây với hộp sạc không dây',
                'Price' => 219.99,
                'Stock' => 150,
                'ImageURL' => 'airpods4_wireless.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Pro 2 Limited Edition',
                'Description' => 'Tai nghe không dây phiên bản giới hạn, chống ồn',
                'Price' => 309.99,
                'Stock' => 90,
                'ImageURL' => 'airpodspro2_limited.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 3rd Gen Refurbished',
                'Description' => 'Tai nghe không dây tân trang với âm thanh không gian',
                'Price' => 149.99,
                'Stock' => 130,
                'ImageURL' => 'airpods3_refurbished.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Max Red',
                'Description' => 'Tai nghe over-ear cao cấp, màu đỏ',
                'Price' => 549.99,
                'Stock' => 40,
                'ImageURL' => 'airpodsmax_red.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 2nd Gen Refurbished',
                'Description' => 'Tai nghe không dây tân trang, giá rẻ',
                'Price' => 99.99,
                'Stock' => 180,
                'ImageURL' => 'airpods2_refurbished.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Pro 2 White',
                'Description' => 'Tai nghe không dây màu trắng, chống ồn cải tiến',
                'Price' => 279.99,
                'Stock' => 170,
                'ImageURL' => 'airpodspro2_white.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods 4th Gen MagSafe',
                'Description' => 'Tai nghe không dây với hộp sạc MagSafe',
                'Price' => 209.99,
                'Stock' => 160,
                'ImageURL' => 'airpods4_magsafe.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 3,
                'ProductName' => 'AirPods Max Black',
                'Description' => 'Tai nghe over-ear cao cấp, màu đen',
                'Price' => 549.99,
                'Stock' => 45,
                'ImageURL' => 'airpodsmax_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // CategoryID = 4: Watch (25 products)
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Ultra 2 Titanium',
                'Description' => 'Đồng hồ thông minh cao cấp cho thể thao và phiêu lưu',
                'Price' => 799.99,
                'Stock' => 60,
                'ImageURL' => 'applewatchultra2_titanium.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 9 41mm Silver',
                'Description' => 'Đồng hồ thông minh với chip S9, màu bạc',
                'Price' => 429.99,
                'Stock' => 100,
                'ImageURL' => 'applewatchseries9_41mm_silver.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch SE 2 40mm Starlight',
                'Description' => 'Đồng hồ thông minh giá rẻ, màu ánh sao',
                'Price' => 249.99,
                'Stock' => 140,
                'ImageURL' => 'applewatchse2_40mm_starlight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 8 45mm Midnight',
                'Description' => 'Đồng hồ thông minh với cảm biến nhiệt độ, màu xanh đêm',
                'Price' => 399.99,
                'Stock' => 120,
                'ImageURL' => 'applewatchseries8_45mm_midnight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Ultra Titanium Black',
                'Description' => 'Đồng hồ thông minh bền bỉ, màu đen titan',
                'Price' => 749.99,
                'Stock' => 50,
                'ImageURL' => 'applewatchultra_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 9 45mm Red',
                'Description' => 'Đồng hồ thông minh với chip S9, màu đỏ',
                'Price' => 449.99,
                'Stock' => 90,
                'ImageURL' => 'applewatchseries9_45mm_red.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch SE 2 44mm Silver',
                'Description' => 'Đồng hồ thông minh giá rẻ, màu bạc',
                'Price' => 279.99,
                'Stock' => 130,
                'ImageURL' => 'applewatchse2_44mm_silver.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 7 41mm Green',
                'Description' => 'Đồng hồ thông minh với màn hình lớn, màu xanh',
                'Price' => 349.99,
                'Stock' => 110,
                'ImageURL' => 'applewatchseries7_41mm_green.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Ultra 2 Ocean Blue',
                'Description' => 'Đồng hồ thông minh cao cấp, dây Ocean Blue',
                'Price' => 799.99,
                'Stock' => 55,
                'ImageURL' => 'applewatchultra2_oceanblue.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 9 41mm Pink',
                'Description' => 'Đồng hồ thông minh với chip S9, màu hồng',
                'Price' => 429.99,
                'Stock' => 95,
                'ImageURL' => 'applewatchseries9_41mm_pink.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch SE 2 40mm Midnight',
                'Description' => 'Đồng hồ thông minh giá rẻ, màu xanh đêm',
                'Price' => 249.99,
                'Stock' => 140,
                'ImageURL' => 'applewatchse2_40mm_midnight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 8 41mm Gold',
                'Description' => 'Đồng hồ thông minh với cảm biến ECG, màu vàng',
                'Price' => 399.99,
                'Stock' => 115,
                'ImageURL' => 'applewatchseries8_41mm_gold.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Ultra Alpine Green',
                'Description' => 'Đồng hồ thông minh bền bỉ, dây Alpine Green',
                'Price' => 749.99,
                'Stock' => 50,
                'ImageURL' => 'applewatchultra_alpinegreen.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 7 45mm Blue',
                'Description' => 'Đồng hồ thông minh với màn hình lớn, màu xanh',
                'Price' => 369.99,
                'Stock' => 100,
                'ImageURL' => 'applewatchseries7_45mm_blue.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 9 45mm Starlight',
                'Description' => 'Đồng hồ thông minh với chip S9, màu ánh sao',
                'Price' => 449.99,
                'Stock' => 90,
                'ImageURL' => 'applewatchseries9_45mm_starlight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch SE 2 44mm Black',
                'Description' => 'Đồng hồ thông minh giá rẻ, màu đen',
                'Price' => 279.99,
                'Stock' => 130,
                'ImageURL' => 'applewatchse2_44mm_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Ultra 2 Trail Loop',
                'Description' => 'Đồng hồ thông minh cao cấp, dây Trail Loop',
                'Price' => 799.99,
                'Stock' => 55,
                'ImageURL' => 'applewatchultra2_trailloop.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 8 45mm Silver',
                'Description' => 'Đồng hồ thông minh với cảm biến nhiệt độ, màu bạc',
                'Price' => 429.99,
                'Stock' => 110,
                'ImageURL' => 'applewatchseries8_45mm_silver.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 7 41mm Red',
                'Description' => 'Đồng hồ thông minh với màn hình lớn, màu đỏ',
                'Price' => 349.99,
                'Stock' => 105,
                'ImageURL' => 'applewatchseries7_41mm_red.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch SE 2 40mm Blue',
                'Description' => 'Đồng hồ thông minh giá rẻ, màu xanh',
                'Price' => 249.99,
                'Stock' => 135,
                'ImageURL' => 'applewatchse2_40mm_blue.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Ultra Starlight',
                'Description' => 'Đồng hồ thông minh bền bỉ, màu ánh sao',
                'Price' => 749.99,
                'Stock' => 50,
                'ImageURL' => 'applewatchultra_starlight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 9 41mm Black',
                'Description' => 'Đồng hồ thông minh với chip S9, màu đen',
                'Price' => 429.99,
                'Stock' => 95,
                'ImageURL' => 'applewatchseries9_41mm_black.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Series 8 41mm Starlight',
                'Description' => 'Đồng hồ thông minh với cảm biến ECG, màu ánh sao',
                'Price' => 399.99,
                'Stock' => 115,
                'ImageURL' => 'applewatchseries8_41mm_starlight.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch SE 2 44mm Red',
                'Description' => 'Đồng hồ thông minh giá rẻ, màu đỏ',
                'Price' => 279.99,
                'Stock' => 130,
                'ImageURL' => 'applewatchse2_44mm_red.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'CategoryID' => 4,
                'ProductName' => 'Apple Watch Ultra 2 Black Titanium',
                'Description' => 'Đồng hồ thông minh cao cấp, màu đen titan',
                'Price' => 799.99,
                'Stock' => 55,
                'ImageURL' => 'applewatchultra2_blacktitanium.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}